### ISSUE TITLE
Import failed using OmekaS v3.2.3

### ISSUE THREAD

**Issue by b0rt** [ivyrze/omeka-s-module-transcript#3]
I tried a test import resulting in this error

```
``` Error
Call to undefined function Vimeo\curl_init()

Details:

Error: Call to undefined function Vimeo\curl_init() in /var/www/html/modules/Transcript/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:519
Stack trace:
#0 /var/www/html/modules/Transcript/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(149): Vimeo\Vimeo->_request()
#1 /var/www/html/modules/Transcript/src/Media/Ingester/Vimeo.php(173): Vimeo\Vimeo->request()
#2 /var/www/html/modules/Transcript/src/Media/Ingester/Vimeo.php(94): Transcript\Media\Ingester\Vimeo->getVideoLinks()
#3 /var/www/html/application/src/Api/Adapter/MediaAdapter.php(169): Transcript\Media\Ingester\Vimeo->ingest()
#4 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(630): Omeka\Api\Adapter\MediaAdapter->hydrate()
#5 /var/www/html/application/src/Api/Adapter/ItemAdapter.php(257): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity()
#6 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(630): Omeka\Api\Adapter\ItemAdapter->hydrate()
#7 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(440): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity()
#8 /var/www/html/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update()
#9 /var/www/html/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute()
#10 /var/www/html/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update()
#11 /var/www/html/application/src/Controller/Admin/ItemController.php(245): Omeka\Mvc\Controller\Plugin\Api->update()
#12 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ItemController->editAction()
#13 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#14 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#15 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#16 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#17 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#18 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#19 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#20 /var/www/html/index.php(22): Laminas\Mvc\Application->run()
#21 {main}
```

Versions:
- omeka s v3.2.3 (via git clone)
- Transcript 4.0.1 (via easy_install)

**Comment by b0rt** [comment]
my mistake, it php curl extnesion was missing
in my case i just had to install it (debian)
```
apt install php-curl
service restart apache
```
